# import colorama
# from colorama import Back, Fore, Style

# colorama.init(autoreset=True)

# def test_color():
#     print(f"{Fore.LIGHTMAGENTA_EX} Light Magenta")
#     print(f"{Fore.MAGENTA} Magenta")
#     print(f"{Fore.LIGHTRED_EX} Light Red")
#     print(f"{Fore.RED} Red ")
#     print(f"{Fore.LIGHTYELLOW_EX} Light Yellow")
#     print(f"{Fore.YELLOW} Yellow")
#     print(f"{Fore.LIGHTWHITE_EX} Light White")
#     print(f"{Fore.WHITE} White")
#     print(f"{Fore.LIGHTGREEN_EX} Light Green ")
#     print(f"{Fore.GREEN} Green")
#     print(f"{Fore.LIGHTCYAN_EX} Light Cyan ")
#     print(f"{Fore.CYAN} Cyan ")
#     print(f"{Fore.LIGHTBLUE_EX} Light Blue")
#     print(f"{Fore.BLUE} Blue ")
#     print(f"{Fore.LIGHTBLACK_EX} Light Black ")
#     print(f"{Fore.BLACK} Black ")

#     print(f"{Back.LIGHTMAGENTA_EX} Light Magenta")
#     print(f"{Back.MAGENTA} Magenta")
#     print(f"{Back.LIGHTRED_EX} Light Red")
#     print(f"{Back.RED} Red ")
#     print(f"{Back.LIGHTYELLOW_EX} Light Yellow")
#     print(f"{Back.YELLOW} Yellow")
#     print(f"{Back.LIGHTWHITE_EX} Light White")
#     print(f"{Back.WHITE} White")
#     print(f"{Back.LIGHTGREEN_EX} Light Green ")
#     print(f"{Back.GREEN} Green")
#     print(f"{Back.LIGHTCYAN_EX} Light Cyan ")
#     print(f"{Back.CYAN} Cyan ")
#     print(f"{Back.LIGHTBLUE_EX} Light Blue")
#     print(f"{Back.BLUE} Blue ")
#     print(f"{Back.LIGHTBLACK_EX} Light Black ")
#     print(f"{Back.BLACK} Black ")

# test_color()